version: '3.7'
services:
  foodtracker-mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    expose:
      - 27017

  foodtracker-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: foodtracker-backend
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - foodtracker-mongodb