version: '3'
services:
    database:
      image: 'mongo'
      container_name: 'foodtracker_mongo'
      environment:
        - MONGO_INITDB_DATABASE= foodtracker_dev_environment
        - MONGO_INITDB_ROOT_USERNAME= testuser
        - MONGO_INTIDB_ROOT_PASSWD= test
      volumes_from:
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./mongo-volume:/data/db
      ports:
        - '27017-27019:27017-27019'